[project]
name = "rag-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.25",
    "ollama>=0.5.1",
    "openai>=1.86.0",
    "pinecone>=7.0.2",
    "pinecone-client>=6.0.0",
    "pypdf2>=3.0.1",
]
